---
## All of possible Elasticsearch configuration options you can find here:
## https://github.com/elastic/elasticsearch/tree/master/docs/reference/modules

cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2
discovery.type: zen
bootstrap.memory_lock: true

